import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
    route("login", "routes/login.tsx"),

    layout("routes/protected.tsx", [
        index("routes/home.tsx"),
        route("suppliers", "routes/suppliers.tsx"),
        route("suppliers/new", "routes/suppliers.new.tsx"),
        route("suppliers/:id", "routes/suppliers.$id.tsx"),
        route("checklist", "routes/checklist.tsx"),
        route("checklist/:id", "routes/checklist.$id.tsx"),
        route("guests", "routes/guests.tsx"),
        route("guests/:id", "routes/guests.$id.tsx"),
        route("budget", "routes/budget.tsx"),
        route("budget/:id", "routes/budget.$id.tsx"),
        route("groomsmen", "routes/groomsmen.tsx"),
        route("groomsmen/new", "routes/groomsmen.new.tsx"),
        route("groomsmen/:id", "routes/groomsmen.$id.tsx"),
        route("bridal-shower", "routes/redirect.bridal-shower.ts"),
        route("celebracao/admin", "routes/bridal-shower.tsx"),
        route("inspirations", "routes/inspirations.tsx"),
        route("assets", "routes/assets.tsx"),
        route("settings", "routes/settings.tsx"),
        route("calendar", "routes/calendar.tsx"),
        route("notifications", "routes/notifications.tsx"),
    ]),

    route("celebracao", "routes/celebration.tsx"),
    route("celebracao/convite/:token", "routes/celebration.invite.$token.ts"),
    route("public/bridal-shower", "routes/redirect.public-celebration.ts"),
    route("public/wedding", "routes/redirect.public-wedding.ts"),
    route("api/subscribe", "routes/api.subscribe.tsx"),
    route("api/inspirations", "routes/api.inspirations.ts"),
    route("api/guests", "routes/api.guests.ts"),
    route("api/dashboard", "routes/api.dashboard.ts"),
    route("api/admin/celebracao", "routes/api.admin.celebration.ts"),
    route("api/admin/celebracao/gifts", "routes/api.admin.celebration-gifts.ts"),
    route("api/reserve-gift", "routes/api.legacy-public-disabled.ts"),
    route("api/groomsmen", "routes/api.groomsmen.ts"),
    route("api/checklist", "routes/api.checklist.ts"),
    route("api/notifications", "routes/api.notifications.ts"),
    route("api/settings", "routes/api.settings.ts"),
    route("api/budget", "routes/api.budget.ts"),
    route("api/bridal-shower", "routes/api.bridal-shower.ts"),
    route("api/bridal-shower-search-guests", "routes/api.legacy-search-disabled.ts"),
    route("api/confirm-presence", "routes/api.legacy-rsvp-disabled.ts"),
    route("api/assets", "routes/api.assets.ts"),
    route("api/public/celebracao/rsvp", "routes/api.public.celebration-rsvp.ts"),
    route("api/public/celebracao/gifts", "routes/api.public.celebration-gifts.ts"),
    route("api/public/celebracao/gift-reservations", "routes/api.public.celebration-gift-reservations.ts"),
    route("api/public/celebracao/gift-reservations/:id", "routes/api.public.celebration-gift-reservations.$id.ts"),
    route("api/public/celebracao/pix-payload", "routes/api.public.celebration-pix-payload.ts"),
] satisfies RouteConfig;
